# Run https://docs.drone.io/quickstart/cli/ pipeline against k3d
name: 'Drone CI'

on:
  pull_request:
  push:

jobs:
  ci:
    name: Continous integration with k3d and drone
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run drone-cli with docker pipeline
        run: |
          bash -x ./drone.sh
